name: Performance Benchmark

on:
  workflow_dispatch:

jobs:
  # Check tests pass on multiple Python and OS combinations
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v5
      with: 
        lfs: true # For test files
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.13
    - name: Set up Java (Windows only)
      if: runner.os == 'Windows'
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 17
    - uses: extractions/setup-just@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv pip install --system .
    - name: Run Performance Benchmark
      run: just benchmark
    - name: Upload Performance Results
      uses: actions/upload-artifact@v4
      with:
        path: "output.csv"
        if-no-files-found: error
